version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: demo-app-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo-app
    ports:
      - "54322:5432"
    volumes:
      - demo-app_dev_data:/var/lib/postgresql/data

volumes:
  demo-app_dev_data:
